# Generated by Django 4.2 on 2025-07-07 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('college', models.CharField(max_length=50)),
                ('branch', models.CharField(choices=[('CS', 'Computer Science'), ('EC', 'Electronics & Communication'), ('ME', 'Mechanical'), ('CV', 'Civil')], max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_domains', models.CharField(choices=[('Java', 'Java - Full Stack Web Development'), ('Python', 'Python - Full Stack Web Development')], max_length=50)),
                ('date_enrolled', models.DateField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.candidate')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.company')),
            ],
        ),
    ]
