# Generated by Django 4.2 on 2025-03-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('usn', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=20)),
                ('sem', models.IntegerField()),
                ('book_name', models.CharField(max_length=50)),
                ('isbn_number', models.IntegerField(unique=True)),
                ('author_name', models.CharField(max_length=50)),
            ],
        ),
    ]
